name: CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    strategy: { fail-fast: false, matrix: { os: [ubuntu-latest, windows-latest], python-version: ['3.10','3.11'] } }
    runs-on: ${{ matrix.os }}
    env: { QT_QPA_PLATFORM: offscreen, PIP_DISABLE_PIP_VERSION_CHECK: 1 }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.python-version }} }
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install --only-binary=:all: "numpy>=1.26,<2"
          python -m pip install --prefer-binary -r requirements.txt
          python -m pip install --prefer-binary pytest pytest-cov mypy ruff
      - name: Lint & types
        run: |
          ruff check app tests
          mypy app --ignore-missing-imports
      - name: Tests
        run: pytest -q --maxfail=1 --disable-warnings --cov=app --cov-report=term-missing
